# Generated by Django 3.2 on 2021-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(default='default-image.jpg', upload_to='static/auctions/listingimgs/'),
        ),
    ]
